import time
print('Second level, Lost Temple!')
time.sleep(2)
print('You found a temple in the jungle...')
time.sleep(2)
print('You walked in and see some angry bees!')
time.sleep(3)
print('System prompt: angry bees, HP: 2, speed: medium, attack power: 1, quantity: 20, distance 8 meters from you.')
time.sleep(3)
print('System reward: cleave, attack power: 70, distance: 50 meters, use input c, blood volume: 50.')
time.sleep(2)
box=input('DOD')
if box == 'c':
    print('Excellent!')
    time.sleep(1)
    print('You cleaved them, and they are all die!')
else:
    print('You only killed one bee, and the others killed you!')
    quit()
time.sleep(2)
print('You go on and on...')
time.sleep(2)
print('You found a chest.')
time.sleep(1)
box=input('Open the chest and press o, do not open and press other.')
if box == 'o':
    print('You opened the chest,')
    time.sleep(1)
    print('And you find a iron sword!')
    time.sleep(1)
    print('System prompt: iron sword, increase attack damage 30, reduce attack power 10.')
    time.sleep(2)
else:
    print('You do not open the chest.')
    time.sleep(2)
print('You see a skeleton behind you!')
time.sleep(2)
print('System prompt: skeleton, HP: 50, speed: slow, attack power: 5, distance 5 meters from you.')
time.sleep(3)
box=input('DOD')
if box == 'd':
    print('You attacked it, and it was die.')
else:
    print('You used a trick, it died and gave you a bow.')
